### ISSUE TITLE
Valgrind memory leak warning in Lua state

### ISSUE THREAD

**Issue by begeekmyfriend** [credosemi/smartsnmp#81]
It is traced that commit d8563c46f4395205db19b47148861b9fddc210b7 has made it while the commit just before it is good.

**Comment by xfguo** [comment]
I don't think it is a memory leak, when you call `exit`, OS will collect all the memory the program used. Valgrind didn't report any memory leak during snmp operations.

Please refer this: http://lua-users.org/lists/lua-l/2009-09/msg00141.html 

Thanks.

**Comment by begeekmyfriend** [comment]
Thank you for your reference. It is lua virtual machine did not exit its main chunk smoothly. So at least it reminds of our adding exit(0) in sig_int_handler() as the cleaning spot. I have tried it and it works OK right now.
